/* app.js */
'use strict';
let gifts=[], reservations={}, categories=[], currentCat='all';
const GUESTBOOK=JSON.parse(localStorage.getItem('ln_gb')||'[]');
async function init(){renderCountdown();setupGuestbook();setupFooterSecret();await loadData();setupGSAP();}
async function loadData(){try{const[gRes,rRes]=await Promise.all([fetch('/api/gifts'),fetch('/api/reservations')]);const g=await gRes.json();const r=await rRes.json();gifts=g.gifts||[];categories=g.categories||[];reservations=r.reservations||{};renderFilterTabs();renderGifts();}catch(e){document.getElementById('gifts-grid').innerHTML='<p class="empty-state">Impossible de charger la liste.</p>';}}
function renderCountdown(){const due=new Date('2026-08-07T00:00:00');const tick=()=>{const d=due-Date.now();if(d<=0)return;document.getElementById('days').textContent=Math.floor(d/86400000);document.getElementById('hours').textContent=Math.floor((d%86400000)/3600000);document.getElementById('minutes').textContent=Math.floor((d%3600000)/60000);document.getElementById('seconds').textContent=Math.floor((d%60000)/1000);};tick();setInterval(tick,1000);}
function renderFilterTabs(){const el=document.getElementById('filter-tabs');el.innerHTML='<button class="filter-tab active" data-cat="all">🎁 Tous</button>';const used=[...new Set(gifts.map(g=>g.category))];categories.filter(c=>used.includes(c.id)).forEach(c=>{const b=document.createElement('button');b.className='filter-tab';b.dataset.cat=c.id;b.textContent=c.i+' '+c.n;el.appendChild(b);});el.addEventListener('click',e=>{const b=e.target.closest('.filter-tab');if(!b)return;el.querySelectorAll('.filter-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentCat=b.dataset.cat;renderGifts();});}
function renderGifts(){const grid=document.getElementById('gifts-grid');const f=currentCat==='all'?gifts:gifts.filter(g=>g.category===currentCat);if(!f.length){grid.innerHTML='<p class="empty-state">Aucun cadeau dans cette catégorie.</p>';updateProgress();return;}grid.innerHTML=f.map(g=>{const r=reservations[g.id];const c=categories.find(x=>x.id===g.category)||{};return`<div class="gift-card${r?' reserved':''}" data-id="${g.id}"><div class="gift-img-wrap">${g.image?`<img src="${esc(g.image)}" alt="${esc(g.name)}" loading="lazy" onerror="this.parentElement.innerHTML='<div class=gift-emoji-fallback>${c.i||'🎁'}</div>'">`:`<div class="gift-emoji-fallback">${c.i||'🎁'}</div>`}${r?'<div class="reserved-badge">✅ Réservé</div>':''}</div><div class="gift-body"><span class="gift-cat-tag">${c.i||''} ${c.n||''}</span><h3 class="gift-name">${esc(g.name)}</h3>${g.note?`<p class="gift-note">${esc(g.note)}</p>`:''}<div class="gift-footer"><span class="gift-price">${g.price?g.price.toFixed(2)+' €':'Prix non renseigné'}</span>${g.url?`<a class="gift-link" href="${esc(g.url)}" target="_blank" rel="noopener">Voir le produit ↗</a>`:''}</div>${r?`<p class="reserved-by">Réservé par <strong>${esc(r.name)}</strong></p>`:`<button class="btn-reserve" onclick="openModal('${g.id}')">Réserver 🎁</button>`}</div></div>`;}).join('');updateProgress();}
function updateProgress(){const t=gifts.length,r=Object.keys(reservations).filter(id=>gifts.find(g=>g.id===id)).length;p=t?Math.round((r/t)*100):0;document.getElementById('progress-fill').style.width=p+'%';document.getElementById('progress-text').textContent=`${r} cadeau${r>1?'x':''} réservé${r>1?'s':''} sur ${t}`;}
let curId=null;
function openModal(id){if(reservations[id])return;curId=id;const g=gifts.find(x=>x.id===id);if(!g)return;const c=categories.find(x=>x.id===g.category)||{};document.getElementById('modal-preview').innerHTML=`<div class="modal-gift-info">${g.image?`<img src="${esc(g.image)}" alt="${esc(g.name)}">`:`<div class="modal-emoji">${c.i||'🎁'}</div>`}<div><p class="modal-gift-name">${esc(g.name)}</p>${g.price?`<p class="modal-gift-price">${g.price.toFixed(2)} €</p>`:''}</div></div>`;document.getElementById('res-form').reset();document.getElementById('modal-overlay').classList.add('active');document.getElementById('res-modal').classList.add('active');document.getElementById('success-modal').classList.remove('active');}
function closeModal(){document.getElementById('modal-overlay').classList.remove('active');['res-modal','success-modal'].forEach(id=>document.getElementById(id).classList.remove('active'));}
document.getElementById('modal-overlay').addEventListener('click',e=>{if(e.target===document.getElementById('modal-overlay'))closeModal();});
document.getElementById('res-form').addEventListener('submit',async e=>{e.preventDefault();const name=document.getElementById('res-name').value.trim();const msg=document.getElementById('res-msg').value.trim();const g=gifts.find(x=>x.id===curId);if(!g)return;try{const r=await fetch('/api/reservations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({itemId:curId,name,message:msg,itemName:g.name,price:g.price})});if(r.ok||r.status===409){reservations[curId]={name,message:msg};renderGifts();document.getElementById('res-modal').classList.remove('active');document.getElementById('success-modal').classList.add('active');setTimeout(closeModal,3000);}}catch{reservations[curId]={name,message:msg};renderGifts();document.getElementById('res-modal').classList.remove('active');document.getElementById('success-modal').classList.add('active');setTimeout(closeModal,3000);}});
function setupGuestbook(){renderGuestbook();document.getElementById('guestbook-form').addEventListener('submit',e=>{e.preventDefault();const n=document.getElementById('guest-name').value.trim();const m=document.getElementById('guest-message').value.trim();if(!n||!m)return;GUESTBOOK.unshift({name:n,msg:m,date:new Date().toISOString()});localStorage.setItem('ln_gb',JSON.stringify(GUESTBOOK));renderGuestbook();e.target.reset();showToast('Message ajouté ! 💌');});}
function renderGuestbook(){const el=document.getElementById('guestbook-list');if(!GUESTBOOK.length){el.innerHTML='<p class="empty-state">Soyez le premier à laisser un message !</p>';return;}el.innerHTML=GUESTBOOK.map(m=>`<div class="gb-message"><div class="gb-header"><span class="gb-name">${esc(m.name)}</span><span class="gb-date">${new Date(m.date).toLocaleDateString('fr-FR',{day:'numeric',month:'long'})}</span></div><p class="gb-text">${esc(m.msg)}</p></div>`).join('');}
function setupFooterSecret(){let c=0,t;document.getElementById('footer-logo').addEventListener('click',()=>{c++;clearTimeout(t);if(c>=3){c=0;window.location.href='/admin';return;}t=setTimeout(()=>{c=0;},600);});}
function setupGSAP(){if(typeof gsap==='undefined')return;gsap.registerPlugin(ScrollTrigger);gsap.from('.hero-content > *',{y:40,opacity:0,duration:1,stagger:0.15,ease:'power3.out'});gsap.from('.countdown-item',{scrollTrigger:{trigger:'.countdown-section',start:'top 80%'},scale:0.6,opacity:0,duration:0.5,stagger:0.1,ease:'back.out(1.7)'});gsap.from('.gift-card',{scrollTrigger:{trigger:'.gifts-section',start:'top 80%'},y:30,opacity:0,duration:0.5,stagger:0.05,ease:'power3.out'});}
function showToast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000);}
function esc(s){const d=document.createElement('div');d.textContent=String(s);return d.innerHTML;}
document.addEventListener('DOMContentLoaded',init);